package com.attendance.system.service;

import com.attendance.system.model.AttendanceRecord;
import com.attendance.system.model.AttendanceSession;
import com.attendance.system.model.User;
import com.attendance.system.repository.AttendanceRecordRepository;
import com.attendance.system.repository.AttendanceSessionRepository;
import com.attendance.system.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.UUID;

@Service
public class AttendanceService {

    @Autowired
    private AttendanceSessionRepository sessionRepository;

    @Autowired
    private AttendanceRecordRepository recordRepository;

    @Autowired
    private UserRepository userRepository;

    // Faculty starts a session
    public AttendanceSession startSession(Long facultyId, String subject, String section, double lat, double lng) {
        User faculty = userRepository.findById(facultyId).orElseThrow(() -> new RuntimeException("Faculty not found"));

        AttendanceSession session = new AttendanceSession();
        session.setFaculty(faculty);
        session.setSubject(subject);
        session.setSection(section);
        session.setStartTime(LocalDateTime.now());
        session.setActive(true);
        session.setLatitude(lat);
        session.setLongitude(lng);
        session.setSessionToken(UUID.randomUUID().toString()); // Use this to secure QR

        return sessionRepository.save(session);
    }

    public void endSession(Long sessionId) {
        AttendanceSession session = sessionRepository.findById(sessionId).orElseThrow();
        session.setActive(false);
        session.setEndTime(LocalDateTime.now());
        sessionRepository.save(session);
    }

    // Student attempts to mark attendance
    public String markAttendance(Long sessionId, Long studentId, double lat, double lng, String qrToken) {
        AttendanceSession session = sessionRepository.findById(sessionId)
                .orElseThrow(() -> new RuntimeException("Session not found"));
        User student = userRepository.findById(studentId).orElseThrow(() -> new RuntimeException("Student not found"));

        // 1. Check if session is active
        if (!session.isActive()) {
            return recordRejection(session, student, lat, lng, "Session Expired");
        }

        // 2. Token Validation (Simple check for now)
        // In real app, qrToken would be a rotating token generated by faculty
        // frontend/backend.
        // For now, let's assume sessionToken validation or time-based OTP.
        // If checking simple token:
        if (!session.getSessionToken().equals(qrToken)) {
            // Or complex validation logic
            return recordRejection(session, student, lat, lng, "Invalid QR Token");
        }

        // 3. One-time check
        if (recordRepository.existsBySessionAndStudentAndStatus(session, student, AttendanceRecord.Status.PRESENT)) {
            return "Already Marked Present"; // No need to log rejection multiple times? Or log duplicate attempt.
        }

        // 4. Geolocation Proximity
        double distance = calculateDistance(session.getLatitude(), session.getLongitude(), lat, lng);
        if (distance > 100) { // 100 meters
            return recordRejection(session, student, lat, lng, "Location Mismatch: Distance " + (int) distance + "m");
        }

        // Success
        AttendanceRecord record = new AttendanceRecord();
        record.setSession(session);
        record.setStudent(student);
        record.setTimestamp(LocalDateTime.now());
        record.setStatus(AttendanceRecord.Status.PRESENT);
        record.setLatitude(lat);
        record.setLongitude(lng);
        recordRepository.save(record);

        return "Attendance Marked Successfully";
    }

    private String recordRejection(AttendanceSession session, User student, double lat, double lng, String reason) {
        AttendanceRecord record = new AttendanceRecord();
        record.setSession(session);
        record.setStudent(student);
        record.setTimestamp(LocalDateTime.now());
        record.setStatus(AttendanceRecord.Status.REJECTED);
        record.setRejectionReason(reason);
        record.setLatitude(lat);
        record.setLongitude(lng);
        recordRepository.save(record);
        return "Failed: " + reason;
    }

    // Haversine Formula for distance in meters
    private double calculateDistance(double lat1, double lon1, double lat2, double lon2) {
        final int R = 6371; // Radius of the earth
        double latDistance = Math.toRadians(lat2 - lat1);
        double lonDistance = Math.toRadians(lon2 - lon1);
        double a = Math.sin(latDistance / 2) * Math.sin(latDistance / 2)
                + Math.cos(Math.toRadians(lat1)) * Math.cos(Math.toRadians(lat2))
                        * Math.sin(lonDistance / 2) * Math.sin(lonDistance / 2);
        double c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
        double distance = R * c * 1000; // convert to meters
        return distance;
    }

    // Admin Stats
    public java.util.Map<String, Object> getAdminStats() {
        java.util.Map<String, Object> stats = new java.util.HashMap<>();
        stats.put("totalStudents", userRepository.countByRole(User.Role.STUDENT));
        stats.put("totalFaculty", userRepository.countByRole(User.Role.FACULTY));
        stats.put("activeSessions", sessionRepository.countByIsActive(true));
        // Simple mock for defaulters for now
        stats.put("defaultersCount", 5);
        return stats;
    }

    // Admin: Create User
    public User createUser(String username, String password, String fullName, String department, User.Role role) {
        if (userRepository.findByUsername(username).isPresent()) {
            throw new RuntimeException("Username already exists");
        }
        User user = new User(null, username, password, fullName, department, role);
        return userRepository.save(user);
    }
}
